root: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
plugins:
  - jest
  - '@typescript-eslint'
env:
  node: true
  jest: true
rules:
  lines-between-class-members:
    - 1
    - always
    - exceptAfterSingleLine: true
  no-console: 0
  func-style: 2
  prefer-spread: 0
  consistent-return: 2
  prefer-arrow-callback:
    - 2
    - allowNamedFunctions: false
      allowUnboundThis: false
  no-unused-vars: 0
  jest/no-disabled-tests: 2
  jest/no-focused-tests: 2
  '@typescript-eslint/no-explicit-any': 2
  '@typescript-eslint/no-empty-interface': 0
  '@typescript-eslint/no-unused-vars':
    - 1
    - ignoreRestSiblings: true
overrides:
  - files:
      - '*.graphql'
    parser: '@graphql-eslint/eslint-plugin'
    plugins:
      - '@graphql-eslint'
    rules:
      '@graphql-eslint/known-type-names': 'error'
